spring:
  datasource:
    first:
      jdbcUrl: ${POSTGRES_DATABASE_FIRST_URL}
      username: ${POSTGRES_DATABASE_FIRST_USER}
      password: ${POSTGRES_DATABASE_FIRST_PASSWORD}
      driver-class-name: org.postgresql.Driver
    second:
      jdbcUrl: ${POSTGRES_DATABASE_SECOND_URL}
      username: ${POSTGRES_DATABASE_SECOND_USER}
      password: ${POSTGRES_DATABASE_SECOND_PASSWORD}
      driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
